spring:
  application:
    name: MidPoint

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

server:
  display-name: MidPoint
  session:
    timeout: 15  # in minutes. By default spring uses seconds, but tomcat/container (not embedded) uses this value
                 # as minutes - so we end up with never expiring session.
  tomcat:
    basedir: ${midpoint.home}
    max-http-post-size: 104857600 # in bytes

auth:
  logout:
    url: /

#security:
#  enable-csrf: false # default for midpoint is true

# more properties with default values can be found here:
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html